name:                mf
version:             0.1.0.0
github:              "githubuser/mf"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"
build-type:          Custom

extra-source-files:
- README.md
- ChangeLog.md
- src/AttributeGrammar.ag
- src/Lexer.x
- src/Parser.y

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/mf#readme>

dependencies:
- base >= 4.7 && < 5
- uuagc >= 0.9.53.1 && < 0.9.54
- array
- containers

build-tools:
- alex
- happy
- uuagc

ghc-options:
- -O0

default-extensions:
- ImportQualifiedPost
- TupleSections
- NamedFieldPuns
- OverloadedStrings
- ScopedTypeVariables
- TypeApplications
- DerivingVia

library:
  source-dirs: src
  dependencies:
  - relude
  - safe-exceptions
  - pretty-simple

executables:
  mf-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mf

tests:
  mf-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mf
